image: docker

services:
  - docker:dind
 
stages:
  - development_deploy
  - deploy
 
developments:
  stage: development_deploy
  only:
    - develop
    - staging
  script:
    - echo running docker-compose down
    - curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - docker-compose down
    - echo running docker-compose up --build
    - docker-compose up --detach
    - echo deployment done
  
deploy:
  stage: deploy
  only:
    - master
  script:
    - echo run deployment
  environment: master
  when: manual