image: docker

services:
  - docker:dind
 
stages:
  - dev_deploy
  - deploy
 
dev_deploy:
  stage: dev_deploy
  only:
    - develop
    - staging
  script:
    - echo running docker-compose down
    - docker-compose down
    - echo running docker-compose up --build
    - docker-compose up --build
    - echo deployment done
  
deploy:
  stage: deploy
  only:
    - master
  script:
    - echo run deployment
  environment: master
  when: manual