image: docker

services:
  - docker:dind

stages:
  - development_deploy
  - deploy
 
developments:
  stage: development_deploy
  only:
    - develop
    - staging
  script:
    - echo "Image building..."
    - sudo docker kill jairusm/lmafrontend
    - sudo docker build -t jairusm/lmafrontend .
    - sudo docker run -p 5000:5000 jairusm/lmafrontend --detach
    - echo "Deployment done."
  
deploy:
  stage: deploy
  only:
    - master
  script:
    - echo run deployment
  environment: master
  when: manual