image: docker

services:
  - docker:dind
 
stages:
  - development_deploy
  - deploy
 
developments:
  stage: development_deploy
  only:
    - develop
    - staging
  script:
    - echo node -v
    - node -v
    - echo npm -v
    - npm -v
    - echo installing docker-compose
    - npm install docker-compose
    - echo running docker-compose down...
    - docker-compose down
    - echo running docker-compose up...
    - docker-compose up --detach
    - echo deployment done
  
deploy:
  stage: deploy
  only:
    - master
  script:
    - echo run deployment
  environment: master
  when: manual