variables:
  REG_NAME: registry.gitlab.com/ideahub-devgroup/lma-sg/frontend:$CI_COMMIT_REF_NAME

stages:
  - build
  - run
  - deploy
 
build_docker_image:
  stage: build
  only:
    - develop
    - staging
  script:
    - sudo docker login -u jairusm -p $runnerPass registry.gitlab.com
    - sudo docker build -t $REG_NAME .
    - sudo docker push $REG_NAME
  tags:
    - lmafrontendbuild

run_docker_image:
  stage: run
  only:
    - develop
    - staging
  script:
    - sudo docker login -u jairusm -p $runnerPass registry.gitlab.com
    - sudo docker pull $REG_NAME
    - sudo docker kill $REG_NAME || true
    - sudo docker rm $REG_NAME || true
    - sudo docker run -dt -p 3000:5000 --name gitlabLMAContainer $REG_NAME
  tags:
    - lmafrontendrun


deploy:
  stage: deploy
  only:
    - master
  script:
    - echo run deployment
  environment: master
  when: manual