image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - development_deploy
  - deploy
 
developments:
  stage: development_deploy
  only:
    - develop
    - staging
  script:
    - echo "Image building..."
    - docker kill jairusm/lmafrontend
    - docker build -t jairusm/lmafrontend .
    - docker run -d -p 5000:5000 jairusm/lmafrontend
    - echo "Deployment done."
  
deploy:
  stage: deploy
  only:
    - master
  script:
    - echo run deployment
  environment: master
  when: manual